apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
spec:
  type: {{ .Values.service.type }} # ClusterIP (Interno)
  ports:
    - port: {{ .Values.service.port }} # Puerto 80 (Externo del servicio)
      targetPort: 8000             # Puerto 8000 (Donde escucha Uvicorn)
      protocol: TCP
      name: http
  selector:
    app: api # Manda tr√°fico a los pods con etiqueta "api"