apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.grafana.service.port }} # Puerto 80
      targetPort: 3000                       # Puerto interno de Grafana
      protocol: TCP
  selector:
    app: grafana