name: CI/CD Pipeline

# 1. ¿Cuándo se activa?
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # TRABAJO 1: CALIDAD (CI)
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install pytest flake8
          if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi

      - name: Linting (Buscar errores de sintaxis)
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # (Acá irían los tests con Pytest, por ahora lo dejamos preparado)
      # - name: Test with pytest
      #   run: pytest

  # TRABAJO 2: ENTREGA (CD) - Solo si pasa el test y es rama main
  build-and-push:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      # --- NUEVO: Emulador para poder compilar para ARM (Mac) ---
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # --- NUEVO: Constructor avanzado ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y Push (API)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          # LA MAGIA: Construir para ambas arquitecturas
          platforms: linux/amd64,linux/arm64 
          tags: ${{ secrets.DOCKER_USERNAME }}/crypto-api:latest, ${{ secrets.DOCKER_USERNAME }}/crypto-api:${{ github.sha }}

      - name: Build y Push (Worker)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          # LA MAGIA: Acá también
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/crypto-worker:latest